"""initial schema

Revision ID: 0703de912a0b
Revises: 
Create Date: 2026-06-06 22:59:19.432996
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0703de912a0b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('avatar_path', sa.Text(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('role', sa.String(length=16), server_default=sa.text("'user'"), nullable=False),
    sa.Column('oauth_provider', sa.Text(), nullable=True),
    sa.Column('oauth_subject', sa.Text(), nullable=True),
    sa.Column('is_anonymized', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('last_seen', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('user','admin')", name='ck_users_role'),
    sa.CheckConstraint('(oauth_provider IS NULL AND oauth_subject IS NULL) OR (oauth_provider IS NOT NULL AND oauth_subject IS NOT NULL)', name='ck_users_oauth_pair'),
    sa.CheckConstraint('bio IS NULL OR char_length(bio) <= 500', name='ck_users_bio_len'),
    sa.CheckConstraint('char_length(username) BETWEEN 3 AND 30', name='ck_users_username_len'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('oauth_provider', 'oauth_subject', name='uq_users_oauth'),
    sa.UniqueConstraint('username')
    )
    op.create_table('attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('uploader_id', sa.UUID(), nullable=False),
    sa.Column('parent_type', sa.String(length=16), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('original_filename', sa.Text(), nullable=False),
    sa.Column('stored_path', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.Text(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("parent_type IS NULL OR parent_type IN ('question','answer')", name='ck_attachments_parent_type'),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_attachments_orphan', 'attachments', ['uploader_id', 'parent_id'], unique=False, postgresql_where=sa.text('parent_id IS NULL'))
    op.create_index('ix_attachments_parent', 'attachments', ['parent_type', 'parent_id'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('parent_type', sa.String(length=16), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('moderation_status', sa.String(length=16), server_default=sa.text("'approved'"), nullable=False),
    sa.Column('moderation_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("moderation_status IN ('pending','approved','rejected')", name='ck_comments_mod_status'),
    sa.CheckConstraint("parent_type IN ('question','answer')", name='ck_comments_parent_type'),
    sa.CheckConstraint('char_length(body) BETWEEN 1 AND 1000', name='ck_comments_body_len'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_comments_parent', 'comments', ['parent_type', 'parent_id'], unique=False)
    op.create_table('friendships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('requester_id', sa.UUID(), nullable=False),
    sa.Column('addressee_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending','accepted','rejected')", name='ck_friendships_status'),
    sa.CheckConstraint('requester_id <> addressee_id', name='ck_friendships_distinct'),
    sa.ForeignKeyConstraint(['addressee_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('friendships_pair_uniq', 'friendships', [sa.literal_column('LEAST(requester_id, addressee_id)'), sa.literal_column('GREATEST(requester_id, addressee_id)')], unique=True)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('receiver_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(body) BETWEEN 1 AND 4000', name='ck_messages_body_len'),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_sender_receiver_created', 'messages', ['sender_id', 'receiver_id', 'created_at'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recipient_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=48), nullable=False),
    sa.Column('subject_type', sa.String(length=16), nullable=True),
    sa.Column('subject_id', sa.UUID(), nullable=True),
    sa.Column('link', sa.Text(), nullable=False),
    sa.Column('coalesce_key', sa.Text(), nullable=True),
    sa.Column('actor_count', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_recipient_read_created', 'notifications', ['recipient_id', 'read_at', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('notifications_coalesce_uniq', 'notifications', ['recipient_id', 'coalesce_key'], unique=True, postgresql_where=sa.text('coalesce_key IS NOT NULL AND read_at IS NULL'))
    op.create_table('questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('accepted_answer_id', sa.UUID(), nullable=True),
    sa.Column('view_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('moderation_status', sa.String(length=16), server_default=sa.text("'approved'"), nullable=False),
    sa.Column('moderation_note', sa.Text(), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("moderation_status IN ('pending','approved','rejected')", name='ck_questions_mod_status'),
    sa.CheckConstraint('cardinality(tags) <= 5', name='ck_questions_tags_count'),
    sa.CheckConstraint('char_length(body) BETWEEN 30 AND 30000', name='ck_questions_body_len'),
    sa.CheckConstraint('char_length(title) BETWEEN 10 AND 200', name='ck_questions_title_len'),
    sa.ForeignKeyConstraint(['accepted_answer_id'], ['answers.id'], name='fk_questions_accepted_answer', ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_questions_search_vector', 'questions', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index('ix_questions_tags', 'questions', ['tags'], unique=False, postgresql_using='gin')
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_token_hash'), 'sessions', ['token_hash'], unique=True)
    op.create_table('votes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('voter_id', sa.UUID(), nullable=False),
    sa.Column('target_type', sa.String(length=16), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("target_type IN ('question','answer')", name='ck_votes_target_type'),
    sa.CheckConstraint('value IN (-1, 1)', name='ck_votes_value'),
    sa.ForeignKeyConstraint(['voter_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('voter_id', 'target_type', 'target_id', name='uq_votes_voter_target')
    )
    op.create_table('ai_conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('answers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_ai_assisted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('moderation_status', sa.String(length=16), server_default=sa.text("'approved'"), nullable=False),
    sa.Column('moderation_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("moderation_status IN ('pending','approved','rejected')", name='ck_answers_mod_status'),
    sa.CheckConstraint('char_length(body) BETWEEN 30 AND 30000', name='ck_answers_body_len'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('user','assistant')", name='ck_ai_messages_role'),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_messages_conversation_created', 'ai_messages', ['conversation_id', 'created_at'], unique=False)
    # ### end Alembic commands ###

    # Hand-added (Alembic autogenerate does not emit triggers): maintain
    # questions.search_vector as a weighted tsvector on insert/update of
    # title/body (spec §5 derived data, task P0-12).
    op.execute(
        """
        CREATE FUNCTION questions_search_vector_update() RETURNS trigger AS $$
        BEGIN
            NEW.search_vector :=
                setweight(to_tsvector('english', coalesce(NEW.title, '')), 'A') ||
                setweight(to_tsvector('english', coalesce(NEW.body, '')), 'B');
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER questions_search_vector_trg
            BEFORE INSERT OR UPDATE OF title, body ON questions
            FOR EACH ROW EXECUTE FUNCTION questions_search_vector_update();
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Hand-added: drop the search_vector trigger and function first (task P0-12).
    op.execute("DROP TRIGGER IF EXISTS questions_search_vector_trg ON questions;")
    op.execute("DROP FUNCTION IF EXISTS questions_search_vector_update();")
    op.drop_index('ix_ai_messages_conversation_created', table_name='ai_messages')
    op.drop_table('ai_messages')
    op.drop_table('answers')
    op.drop_table('ai_conversations')
    op.drop_table('votes')
    op.drop_index(op.f('ix_sessions_token_hash'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('ix_questions_tags', table_name='questions', postgresql_using='gin')
    op.drop_index('ix_questions_search_vector', table_name='questions', postgresql_using='gin')
    op.drop_table('questions')
    op.drop_index('notifications_coalesce_uniq', table_name='notifications', postgresql_where=sa.text('coalesce_key IS NOT NULL AND read_at IS NULL'))
    op.drop_index('ix_notifications_recipient_read_created', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_messages_sender_receiver_created', table_name='messages')
    op.drop_table('messages')
    op.drop_index('friendships_pair_uniq', table_name='friendships')
    op.drop_table('friendships')
    op.drop_index('ix_comments_parent', table_name='comments')
    op.drop_table('comments')
    op.drop_index('ix_attachments_parent', table_name='attachments')
    op.drop_index('ix_attachments_orphan', table_name='attachments', postgresql_where=sa.text('parent_id IS NULL'))
    op.drop_table('attachments')
    op.drop_table('users')
    # ### end Alembic commands ###
